### ISSUE TITLE
Maybe "borrow" from the BioC vignettes?

### ISSUE THREAD

**Issue by eddelbuettel** [yixuan/prettydoc#1]
Loving this project -- immediately installed when I saw the CRANberries notice earlier.

One format I have played with is the [BioCStyle](http://bioconductor.org/packages/release/bioc/html/BiocStyle.html) style which is also more lightweight.  Maybe include (with attribution) or borrow from it?  Or maybe just refer to it from the documentation as "yet another light(er)weight alternative" ?

**Comment by yixuan** [comment]
Hi Dirk,

This is great -- I was unware of this template before I wrote `prettydoc`. I'll contact the authors later to see what is the best way to "borrow" from. Probably including it in `prettydoc` is more convenient for non-BioC R users.

Another R Markdown template is the [tufte](https://github.com/rstudio/tufte) package by @yihui. This package can be easily installed from R, so I may refer to it in the documentation in future version of `prettydoc`.

**Comment by eddelbuettel** [comment]
Yes, precisely -- I tend not to go to BioC or update so having it via prettydoc would be great.

**Comment by yixuan** [comment]
According to the discussion in https://github.com/Bioconductor/BiocStyle/issues/10 we probably would better just refer to it.

**Comment by eddelbuettel** [comment]
Thanks for that.  Was unaware of their intent to going full featured.  I guess there is room for both.

Worst, once they change, you could resurrect their theme (with attribution, maybe different colours) but it is not a must have.  I just wanted to point this out to you -- so thanks for following up.   I agree that closing it is the best course of action now.

**Comment by yixuan** [comment]
I guess one of the major concerns is the identity of Bioconductor, so the preferred way may be to include templates that have noticeably different styles from BiocStyle. 😏
