### ISSUE TITLE
Italic not working

### ISSUE THREAD

**Issue by leo-filgueira** [yixuan/prettydoc#11]
I'm using prettydoc theme cayman, and I've done the following:

```
---
title: "Title"
author: "Author"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

*italic* text 
``` 
But the word "italic" is normal in HTML.

![italico](https://user-images.githubusercontent.com/33987660/44425570-9b8eb880-a562-11e8-855a-98cd0a61e1ce.png)

**Comment by leo-filgueira** [comment]
My session info:

```
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Portuguese_Brazil.1252 
[2] LC_CTYPE=Portuguese_Brazil.1252   
[3] LC_MONETARY=Portuguese_Brazil.1252
[4] LC_NUMERIC=C                      
[5] LC_TIME=Portuguese_Brazil.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] prettydoc_0.2.1

loaded via a namespace (and not attached):
 [1] compiler_3.4.0  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2
 [5] htmltools_0.3.6 tools_3.4.0     yaml_2.2.0      Rcpp_0.12.18   
 [9] stringi_1.2.4   rmarkdown_1.10  knitr_1.20      stringr_1.3.1  
[13] digest_0.6.15   evaluate_0.11 
```

**Comment by EandrewJones** [comment]
I'm running into the same issue. However, italics works fine when you open the html document in a browser (at least in chrome).
![prettydoc_italic1](https://user-images.githubusercontent.com/41238273/44496193-686f2680-a641-11e8-8fa2-cf787c18b06c.png)
![prettydoc_italic2](https://user-images.githubusercontent.com/41238273/44496194-686f2680-a641-11e8-9177-f0095b9879dd.png)

**Comment by yixuan** [comment]
Interestingly it works well for me, even in the RStudio browser.

![image](https://user-images.githubusercontent.com/216398/45032403-b7dd2b80-b01f-11e8-9f4e-d82d4b748327.png)

@leo-filgueira Can you reproduce the issue in any other major browsers?

**Comment by leo-filgueira** [comment]
@yixuan , I've opened in Chrome and worked. Maybe it's a problem in my RStudio browser version
