### ISSUE TITLE
highlight option not working for python code chunk?

### ISSUE THREAD

**Issue by nietzschetmh** [yixuan/prettydoc#12]
Hi, i like prettydoc a lot.

I added a `python` code chunk and `R` code chunk. It seems the highlight is only working for `R` code chunk.

Here's the **Python** code chunk

![image](https://user-images.githubusercontent.com/3357585/46690465-5edd5600-cbd0-11e8-9b54-9783b7e033da.png)

Here's the **R** code chunk.
![image](https://user-images.githubusercontent.com/3357585/46690526-83393280-cbd0-11e8-9f23-76c579f764ab.png)

**Comment by yixuan** [comment]
I feel it is more like a pandoc problem, similar to https://github.com/jgm/pandoc/issues/2054.
You can see that the constants and strings were indeed highlighted, but pandoc didn't emphasize on member functions and keywords like `import`.

**Comment by nietzschetmh** [comment]
Thanks yixuan. In that case, i think we could only make ad hoc changes and this is not related to prettydoc.
