### ISSUE TITLE
add support for  # title {.tabset} 

### ISSUE THREAD

**Issue by Leo-Lee15** [yixuan/prettydoc#13]
Thanks for this awesome package!

I've found the `# title {.tabset}` feature in plain rmarkdown very useful (see the following screenshot for example). But it seems this feature is not supported in `prettydoc` package. 

![image](https://user-images.githubusercontent.com/18102092/49328377-9651f880-f5aa-11e8-9465-b35db5192f38.png)

Would you mind considering adding this feature into the `prettydoc` package.? Thanks!

**Comment by yixuan** [comment]
The difficulty is that tabset heavily depends on the Bootstrap library, which `prettydoc` intentionally tries to avoid. Perhaps there are other nice rmarkdown templates that are based on Bootstrap and have this feature built in.

**Comment by Leo-Lee15** [comment]
Thanks!
