### ISSUE TITLE
html associated XXX_files directory

### ISSUE THREAD

**Issue by bernardkaplan** [yixuan/prettydoc#15]
Hi,

When I `render` the following document `test.md` a directory `test_files` is generated along the html file `test.html`. 

- `build.R`
```
rmarkdown::render("test.md")
```

`test.md`
```md
---
title: "Test"
output:
  prettydoc::html_pretty
---
```

`test_files` contains fonts, images and styles not even referenced in the html.

Is it possible to generate a single html file without the XXX_files folder ?

Regards,

Bernard

**Comment by yixuan** [comment]
Thanks. It looks like a bug of `prettydoc`: if your document includes a figure, then the `XXX_files` folder does not show up. I'll try to fix it.

**Comment by yixuan** [comment]
This should have been fixed by https://github.com/rstudio/rmarkdown/pull/1665.
