### ISSUE TITLE
Problem properly selecting parts of code chunks (in browser)

### ISSUE THREAD

**Issue by RemPsyc** [yixuan/prettydoc#16]
I've made a detailed post (with screenshots and sample code) on [stackoverflow](https://stackoverflow.com/questions/58667538/how-to-properly-select-code-in-browser-in-textbox-using-prettydoc-package-gene), and someone commented that he could confirm the problem, thought it was a bug, and that I should post it here. But basically I'm not able to select part of text from code chunks using common browsers such as Chrome, Edge, or Explorer, though I don't have this issue when not using prettydoc.

**Comment by yixuan** [comment]
Yeah, I can reproduce this. This is the first time I realize this issue as I typically use Firefox, which sees no problem in selecting the code.

Let me take a look and see where it comes from.

**Comment by yixuan** [comment]
I believe this is related to https://github.com/jgm/pandoc/issues/4278. The problem is that some versions of Pandoc add a `pointer-events: none;` attribute to the code lines, making the text unselectable. 

I have made a patch to `prettydoc` and the new version is on the way to CRAN.
