### ISSUE TITLE
How to Add Title for Table of Contents

### ISSUE THREAD

**Issue by steveb-cirina** [yixuan/prettydoc#20]
Is there a way to add a title for the table of contents using prettydoc ?

Something like the following below where the `toctitle` (assuming this is the YAML variable for this example) is set to **Contents**:

**Contents**

- Item 1
- Item 2

**Comment by yixuan** [comment]
Hi @steveb-cirina, this feature has been added in the development version of `prettydoc`. See the example here: https://github.com/yixuan/prettydoc/blob/master/vignettes/cayman.Rmd.

Right now this option is only supported in the `cayman` and `architect` themes, and I will add it for other themes too when I get some time.
