### ISSUE TITLE
cayman css  :first-child for .main-content interferes with leaflet (i.e.)

### ISSUE THREAD

**Issue by maybegeek** [yixuan/prettydoc#25]
Hi there,

`cayman` scss does not scope the :first-child selector enough, so html-widget in rmarkdown, i.e. leaflet, getting their `margin-top: 0` too.

```{scss}
.main-content {
// ...
  :first-child {
    margin-top: 0;
  }
// ...
}
```

https://github.com/yixuan/prettydoc/blob/4810d4f9c332dd3d527b613464af739987626de3/not_in_package/cayman/cayman.scss#L259

`architect` scss, on the other hand, uses this:

```{scss}
#main-content {
  > :first-child {
    margin-top: 0;
  }
// ...
}
```
which converts to: `#main-content > :first-child {margin-top: 0;}` and therefore does not descend further down the dom.

I would appreciate the `>` in cayman too.

**Comment by yixuan** [comment]
Thank you! Would you like to submit a quick fix if you know how to do it?

**Comment by maybegeek** [comment]
Hi @yixuan,

thanks for your answer. I would propose https://github.com/yixuan/prettydoc/pull/26
