### ISSUE TITLE
Alignment of Table of Contents

### ISSUE THREAD

**Issue by sainathadapa** [yixuan/prettydoc#3]
Table of Contents are aligned to the left side of the page, unlike the actual content. Please check the attached image.
![rstudio -tmp-rtmpr1m6zk-preview-58b03178925a dir-stubthat html_002](https://cloud.githubusercontent.com/assets/4915751/17641479/b42d688c-613f-11e6-87dc-ac0ee9a0bedf.png)

**Comment by yixuan** [comment]
Yes, this is what I commented in #2 . It has been fixed in the recent github version.

**Comment by sainathadapa** [comment]
Ok. Thanks. and also, thanks for the package!

**Comment by yixuan** [comment]
You are welcome. Hope this helps.
