### ISSUE TITLE
Change styling attributes for code messages/warnings?

### ISSUE THREAD

**Issue by ayushnoori** [yixuan/prettydoc#30]
Is it possible to change the background color or other styling attributes for the `div` containing the code output/messages/warnings? Please see below - both the code and the corresponding message look similar. Thanks!

![image](https://user-images.githubusercontent.com/43010710/106573067-098a8880-64ee-11eb-9584-2c3556258137.png)

**Comment by maybegeek** [comment]
Hi @ayushnoori ,

I wanted this changed too. For the moment I am using these lines in my additional css file for `cayman`:

```{css}
div.sourceCode {
  margin-bottom: 0;
}
div.sourceCode ~ pre {
  margin-bottom: 1.2em;
  background-color: white;
  font-size: 0.7em;
}
div.sourceCode ~ pre::before {
  content: "R {message|warning|error} ...";
  display: block;
  font-style: italic;
  text-decoration: underline;
  padding-bottom: 0.3em;
}
```

![cayman theme, additional css for R messages ...](https://user-images.githubusercontent.com/1978651/106718487-6a56b580-6601-11eb-869f-23107c823f01.png)

perhaps that that helps.
christoph

**Comment by ayushnoori** [comment]
Hi @maybegeek - thanks, this is a great idea. Would you be willing to share your extra CSS file? I'm interested in any additional enhancements to the base Cayman theme.

Or, any recommendations for where to find a good theme file that can be used out-of-the-box to knit my document? I'm willing to use [`rmarkdown::html_document`](https://bookdown.org/yihui/rmarkdown/html-document.html) rather than `prettydoc` as I'm not concerned about increased file size, but wasn't able to find a [Bootswatch](https://bootswatch.com/3/) theme that could rival the aesthetic appeal of the `prettydoc` implementation of the Cayman theme.

**Comment by maybegeek** [comment]
Hi @ayushnoori ,
my opinionated css edits (for `prettydoc` 0.4.1, cayman) are here:

https://github.com/maybegeek/css-prettydoc-cayman-anpassungen

have fun with your docs!

Christoph

**Comment by ayushnoori** [comment]
Thanks Christoph! I appreciate it.

**Comment by yixuan** [comment]
Thank you @ayushnoori @maybegeek for the discussion. I apologize that I'm quite busy this month and cannot find time to look at this carefully. This seems to be a good feature for prettydoc, and I will think about it when I get some time.

**Comment by ayushnoori** [comment]
@yixuan, no worries - thanks for developing such a great package which makes writing good documentation so much easier. Inspired by @maybegeek, I am working on my own style sheet to supplement the Cayman theme, am happy to contribute or make available at my own repo if that would be helpful. For example, below is a rough draft of my implementation for a Table of Contents header:

``` css
/* TABLE OF CONTENTS */

div.toc-box {
  margin-top: 1rem;
}

div.toc::before {
  content: "Table of Contents";
  margin-top: 2rem;
  font-weight: 400;
  color: #159957;
  font-size: 1.5em;
}

div.toc {
  padding-top: 4rem;
}
```

**Comment by ayushnoori** [comment]
Hi @yixuan - wanted to follow-up about potentially making this a permanent feature of `prettydoc`. I've found that Christoph's solution doesn't always work for all languages (adds extra space w/ bash, for example). Thanks!
