### ISSUE TITLE
'self_contained: false' not working correctly

### ISSUE THREAD

**Issue by jemus42** [yixuan/prettydoc#4]
I created some sample renders of your themes, and I wanted to move the assets to a dedicated directory to remove redundancy, hence the `self_contained: false`.  

However, when pushing to my server, the files don't render correctly.
- [Directory with examples, including `assets` folder also holding assets for other documents](http://public.tadaa-data.de/QM/pruefungstutorien/qm2_sose_16/)
- [Example output](http://public.tadaa-data.de/QM/pruefungstutorien/qm2_sose_16/Presentation_web_pretty_cayman.html)

I checked the source HTML and in the header it specifies a CSS file located in what I assume to be my local machine's temp dir:

![](http://dump.jemu.name/3loZG.png)

Is this a solvable issue or are these templates not meant to be used with `self_contained: false`?

**Comment by yixuan** [comment]
I think this is fixable. I'll take a look later. Thanks for the report.

**Comment by yixuan** [comment]
Hi @jemus42 , I believe that this issue has been fixed in the most recent github version. Could you have a try to test it? Thanks.
