### ISSUE TITLE
tabset sections do not work

### ISSUE THREAD

**Issue by abnormally-distributed** [yixuan/prettydoc#9]
The tabset tag beside a section is supposed to make content in the subheadings appear as tabs. I know prettydoc doesn't support certain features such as floating table of contents, but the documentation makes no statements about not supporting tabset sections, so I assume it's supposed to. I can't get it to work. Instead it appears as a normal section.  Below is some code that reproduces it. 

I'm using the theme architect, if it helps. Rmarkdown is updated to the latest version. Apologies for the formatting. I can't seem to get it to look like a script because the site automatically formats the markdown unless I bold the hashtags and such, which makes it appear all in-line. 
> ---
> title: "example"
> author: "me"
> output: 
>    prettydoc::html_pretty:
>     theme: architect
> ---
>
> ## tabset.section {.tabset}
> 
> ### One
>```{r}
>plot(Sepal.Width ~ . , data=iris)
>```
>### Two
>```{r}
>plot(Sepal.Length ~ . , data=iris)
>```
>

**Comment by yixuan** [comment]
This should be a Bootstrap-only feature. I'll document this limitation later. Thanks for reporting.

**Comment by jodjo86** [comment]
I would find it very useful that tabset sections be supported in prettydoc or add something similar.

**Comment by uramnama** [comment]
that would be amazing

**Comment by S-UP** [comment]
Agreed. Was using prettydoc but now have to switch to another package as using tabs was very important to de-clutter the document.

**Comment by harrelfe** [comment]
Failure to support tabsets unfortunately makes me have to quit using prettydoc.  Not having floating table of contents is also a major limitation of the model.

**Comment by yixuan** [comment]
Yeah I understand this is a nice feature. It is just not easy to integrate with the current templates. I may explore the possibility in the future, but for now `rmarkdown::html_document()` is the most feature-complete output format.

**Comment by moldach** [comment]
> Agreed. Was using prettydoc but now have to switch to another package as using tabs was very important to de-clutter the document.

What did you switch to @S-UP ? 😅

**Comment by Wesley-M** [comment]
Very late to the party. Regardless, if you've come this far, just look up the ["rmdformats"](https://juba.github.io/rmdformats/) package.
